/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
export const CallStatus = IDL.Variant({
  'active' : IDL.Null,
  'calling' : IDL.Null,
  'ended' : IDL.Null,
  'declined' : IDL.Null,
});
export const CallSession = IDL.Record({
  'id' : IDL.Text,
  'status' : CallStatus,
  'receiverICE' : IDL.Vec(IDL.Text),
  'answerSDP' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'callerICE' : IDL.Vec(IDL.Text),
  'receiverUsername' : IDL.Text,
  'callType' : CallType,
  'callerId' : IDL.Principal,
  'receiverId' : IDL.Principal,
  'callerUsername' : IDL.Text,
  'offerSDP' : IDL.Opt(IDL.Text),
});
export const CallHistory = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'declined' : IDL.Null,
  }),
  'receiverUsername' : IDL.Text,
  'callType' : CallType,
  'callerId' : IDL.Principal,
  'receiverId' : IDL.Principal,
  'callerUsername' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'coupleCode' : IDL.Text,
  'paired' : IDL.Bool,
  'partner' : IDL.Opt(IDL.Principal),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaItem = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'uploaderUsername' : IDL.Text,
  'uploader' : IDL.Principal,
  'timestampNanos' : IDL.Int,
});
export const Message = IDL.Record({
  'read' : IDL.Bool,
  'senderUsername' : IDL.Text,
  'messageText' : IDL.Text,
  'senderPrincipal' : IDL.Principal,
  'timestamp' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addICECandidate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCallSession' : IDL.Func(
      [IDL.Principal, CallType],
      [IDL.Variant({ 'ok' : CallSession, 'err' : IDL.Text })],
      [],
    ),
  'deleteAllUserData' : IDL.Func([], [], []),
  'deleteMedia' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateCoupleCode' : IDL.Func([], [], []),
  'getActiveCallSession' : IDL.Func([], [IDL.Opt(CallSession)], ['query']),
  'getCallHistory' : IDL.Func([], [IDL.Vec(CallHistory)], ['query']),
  'getCallSession' : IDL.Func([IDL.Text], [IDL.Opt(CallSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryMedia' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getPartnerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPaired' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesRead' : IDL.Func([], [], []),
  'pairWithCode' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [], []),
  'setAnswer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setOffer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCallStatus' : IDL.Func(
      [IDL.Text, CallStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadMedia' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CallType = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
  const CallStatus = IDL.Variant({
    'active' : IDL.Null,
    'calling' : IDL.Null,
    'ended' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CallSession = IDL.Record({
    'id' : IDL.Text,
    'status' : CallStatus,
    'receiverICE' : IDL.Vec(IDL.Text),
    'answerSDP' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'callerICE' : IDL.Vec(IDL.Text),
    'receiverUsername' : IDL.Text,
    'callType' : CallType,
    'callerId' : IDL.Principal,
    'receiverId' : IDL.Principal,
    'callerUsername' : IDL.Text,
    'offerSDP' : IDL.Opt(IDL.Text),
  });
  const CallHistory = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'missed' : IDL.Null,
      'ended' : IDL.Null,
      'declined' : IDL.Null,
    }),
    'receiverUsername' : IDL.Text,
    'callType' : CallType,
    'callerId' : IDL.Principal,
    'receiverId' : IDL.Principal,
    'callerUsername' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'coupleCode' : IDL.Text,
    'paired' : IDL.Bool,
    'partner' : IDL.Opt(IDL.Principal),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaItem = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'uploaderUsername' : IDL.Text,
    'uploader' : IDL.Principal,
    'timestampNanos' : IDL.Int,
  });
  const Message = IDL.Record({
    'read' : IDL.Bool,
    'senderUsername' : IDL.Text,
    'messageText' : IDL.Text,
    'senderPrincipal' : IDL.Principal,
    'timestamp' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addICECandidate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCallSession' : IDL.Func(
        [IDL.Principal, CallType],
        [IDL.Variant({ 'ok' : CallSession, 'err' : IDL.Text })],
        [],
      ),
    'deleteAllUserData' : IDL.Func([], [], []),
    'deleteMedia' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateCoupleCode' : IDL.Func([], [], []),
    'getActiveCallSession' : IDL.Func([], [IDL.Opt(CallSession)], ['query']),
    'getCallHistory' : IDL.Func([], [IDL.Vec(CallHistory)], ['query']),
    'getCallSession' : IDL.Func([IDL.Text], [IDL.Opt(CallSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryMedia' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getPartnerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPaired' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesRead' : IDL.Func([], [], []),
    'pairWithCode' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [], []),
    'setAnswer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setOffer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCallStatus' : IDL.Func(
        [IDL.Text, CallStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadMedia' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };