/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallHistory {
  'id' : string,
  'status' : { 'missed' : null } |
    { 'ended' : null } |
    { 'declined' : null },
  'receiverUsername' : string,
  'callType' : CallType,
  'callerId' : Principal,
  'receiverId' : Principal,
  'callerUsername' : string,
  'durationSeconds' : bigint,
  'timestamp' : bigint,
}
export interface CallSession {
  'id' : string,
  'status' : CallStatus,
  'receiverICE' : Array<string>,
  'answerSDP' : [] | [string],
  'createdAt' : bigint,
  'callerICE' : Array<string>,
  'receiverUsername' : string,
  'callType' : CallType,
  'callerId' : Principal,
  'receiverId' : Principal,
  'callerUsername' : string,
  'offerSDP' : [] | [string],
}
export type CallStatus = { 'active' : null } |
  { 'calling' : null } |
  { 'ended' : null } |
  { 'declined' : null };
export type CallType = { 'video' : null } |
  { 'voice' : null };
export type ExternalBlob = Uint8Array;
export interface MediaItem {
  'id' : string,
  'blob' : ExternalBlob,
  'mimeType' : string,
  'uploaderUsername' : string,
  'uploader' : Principal,
  'timestampNanos' : bigint,
}
export interface Message {
  'read' : boolean,
  'senderUsername' : string,
  'messageText' : string,
  'senderPrincipal' : Principal,
  'timestamp' : string,
}
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'coupleCode' : string,
  'paired' : boolean,
  'partner' : [] | [Principal],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addICECandidate' : ActorMethod<
    [string, string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCallSession' : ActorMethod<
    [Principal, CallType],
    { 'ok' : CallSession } |
      { 'err' : string }
  >,
  'deleteAllUserData' : ActorMethod<[], undefined>,
  'deleteMedia' : ActorMethod<[string], boolean>,
  'generateCoupleCode' : ActorMethod<[], undefined>,
  'getActiveCallSession' : ActorMethod<[], [] | [CallSession]>,
  'getCallHistory' : ActorMethod<[], Array<CallHistory>>,
  'getCallSession' : ActorMethod<[string], [] | [CallSession]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryMedia' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<MediaItem>
  >,
  'getMessages' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<Message>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getPartnerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPaired' : ActorMethod<[], boolean>,
  'markMessagesRead' : ActorMethod<[], undefined>,
  'pairWithCode' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string], undefined>,
  'setAnswer' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setOffer' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCallStatus' : ActorMethod<
    [string, CallStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadMedia' : ActorMethod<[ExternalBlob, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];